node: historia
label: "História"
department: "História"
source: "DSpace/UFCG"
collections:
  col_riufcg_56: "Mestrado em História - PPGH UFCG"
  col_riufcg_35482: "Doutorado em História - DINTER UFCG/USP"
