node: eletrica
label: "Engenharia Elétrica"
department: "Engenharia Elétrica"
source: "DSpace/UFCG"
collections:
  col_riufcg_49: "Mestrado em Engenharia Elétrica"
  col_riufcg_50: "Doutorado em Engenharia Elétrica"
