services:
  qdrant_eletrica:
    image: qdrant/qdrant:latest
    container_name: qdrant_eletrica
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage/eletrica:/qdrant/storage

  qdrant_quimica:
    image: qdrant/qdrant:latest
    container_name: qdrant_quimica
    restart: unless-stopped
    ports:
      - "6334:6333"
    volumes:
      - ./qdrant_storage/quimica:/qdrant/storage

  qdrant_computacao:
    image: qdrant/qdrant:latest
    container_name: qdrant_computacao
    restart: unless-stopped
    ports:
      - "6335:6333"
    volumes:
      - ./qdrant_storage/computacao:/qdrant/storage

  qdrant_historia:
    image: qdrant/qdrant:latest
    container_name: qdrant_historia
    restart: unless-stopped
    ports:
      - "6336:6333"
    volumes:
      - ./qdrant_storage/historia:/qdrant/storage

  qdrant_linguagem_ensino:
    image: qdrant/qdrant:latest
    container_name: qdrant_linguagem_ensino
    restart: unless-stopped
    ports:
      - "6337:6333"
    volumes:
      - ./qdrant_storage/linguagem_ensino:/qdrant/storage
