node: linguagem_ensino
label: "Linguagem e Ensino"
department: "Linguagem e Ensino"
source: "DSpace/UFCG"
collections:
  col_riufcg_57: "Mestrado em Linguagem e Ensino"
  col_riufcg_22945: "Doutorado em Linguagem e Ensino"
